import { normalizeRows } from './data-model.js';
import { buildModelFromWorkbook, loadWorkbook } from './xlsx-loader.js';
import { generateTimetable } from './scheduler.js';
import { buildExportDocument, downloadPdf } from './export.js';
import { renderShell, renderSetup, renderGenerated, renderTeacherTimetable, renderLabTimetable, renderConflictPanel, renderManualPanel } from './ui.js';

const state = { model: null, result: null, selectedClass: '', template: 'class', view: 'class', manualMode: false };
const content = () => document.querySelector('#content');
const toast = message => { const region = document.querySelector('#toast-region'); const item = document.createElement('div'); item.className = 'toast'; item.textContent = message; region.append(item); setTimeout(() => item.remove(), 3200); };
const setModel = model => { state.model = model; state.selectedClass = model.classes[0] || ''; localStorage.setItem('rpsit-model', JSON.stringify(model)); document.querySelector('#class-selector').innerHTML = model.classes.map(c => `<option value="${c}">${c}</option>`).join(''); document.querySelector('#class-selector').disabled = false; document.querySelector('#generate-button').disabled = false; content().innerHTML = renderSetup({ ...model, activeClass: state.selectedClass, filename: state.filename }); bindSetup(); toast(`Loaded ${model.classes.length} class${model.classes.length === 1 ? '' : 'es'}.`); };
const rerenderSetup = () => { content().innerHTML = renderSetup({ ...state.model, activeClass: state.selectedClass, filename: state.filename }); bindSetup(); };
const bindSetup = () => { document.querySelector('#file-input')?.addEventListener('change', handleFile); document.querySelector('#validate-button')?.addEventListener('click', generate); document.querySelectorAll('.template-option:not(:disabled)').forEach(button => button.addEventListener('click', () => { state.template = button.dataset.template; document.querySelectorAll('.template-option').forEach(x => x.classList.toggle('selected', x === button)); })); document.querySelectorAll('[data-staff-hod]').forEach(button => button.addEventListener('click', () => { const name = button.dataset.staffHod; Object.values(state.model.teachers).forEach(person => { person.isHod = person.name === name; }); state.model.staff = Object.values(state.model.teachers); rerenderSetup(); toast(`${name} marked as HOD. Period 1 is excluded.`); })); document.querySelectorAll('[data-staff-cc]').forEach(select => select.addEventListener('change', () => { const person = state.model.teachers[select.dataset.staffCc] || Object.values(state.model.teachers).find(item => item.name === select.dataset.staffCc); if (!person) return; person.ccFor = select.value ? [select.value] : []; state.model.staff = Object.values(state.model.teachers); toast(`${person.name} CC assignment updated.`); })); document.querySelectorAll('[data-extracurricular]').forEach(input => input.addEventListener('change', () => { const subject = state.model.subjects.find(item => item.id === input.dataset.extracurricular); if (!subject) return; subject.isExtracurricular = input.checked; localStorage.setItem('rpsit-model', JSON.stringify(state.model)); rerenderSetup(); toast(`${subject.name} set as ${input.checked ? 'extracurricular' : 'theory'}.`); })); document.querySelectorAll('[data-lab-day], [data-lab-period]').forEach(select => select.addEventListener('change', () => { const subjectId = select.dataset.labDay || select.dataset.labPeriod; const lab = state.model.labs.find(item => item.subjectId === subjectId); const subject = state.model.subjects.find(item => item.id === subjectId); if (!lab || !subject) return; const daySelect = document.querySelector(`[data-lab-day="${CSS.escape(subjectId)}"]`); const periodSelect = document.querySelector(`[data-lab-period="${CSS.escape(subjectId)}"]`); lab.day = daySelect.value; lab.startPeriod = periodSelect.value ? Number(periodSelect.value) : null; lab.length = subject.labPeriods || lab.length || 2; subject.labDay = lab.day; subject.labStart = lab.startPeriod; localStorage.setItem('rpsit-model', JSON.stringify(state.model)); toast(lab.day && lab.startPeriod ? `${subject.name} fixed to ${lab.day}, Period ${lab.startPeriod}.` : `${subject.name} will be placed automatically.`); })); };
async function handleFile(event) { const file = event.target.files[0]; if (!file) return; const error = document.querySelector('#upload-error'); try { const model = await buildModelFromWorkbook(file); state.filename = file.name; setModel(model); } catch (err) { error.hidden = false; error.textContent = err.validation?.missing?.length ? `Missing columns: ${err.validation.missing.join(', ')}` : err.message; toast('Upload needs attention.'); } }
function selectedSchedule() { return state.result?.schedules?.[state.selectedClass] || Object.values(state.result?.schedules || {})[0]; }
function renderCurrentView() { if (!state.result) { content().innerHTML = renderSetup(state.model ? { ...state.model, activeClass: state.selectedClass, filename: state.filename } : null); bindSetup(); return; } if (state.view === 'teacher') content().innerHTML = renderTeacherTimetable(state.result, state.model); else if (state.view === 'lab') content().innerHTML = renderLabTimetable(state.result, state.model, state.selectedClass); else content().innerHTML = renderGenerated(selectedSchedule(), state.model, state.result.diagnostics); if (state.view === 'class') bindGenerated(); }
function openView(view) { if (!state.model) { toast('Upload a workbook first.'); return; } if (!state.result) state.result = generateTimetable(state.model); state.view = view; document.querySelectorAll('.rail-item').forEach(item => item.classList.toggle('active', item.dataset.view === view)); document.querySelector('h1').textContent = view === 'teacher' ? 'Teacher Timetable' : view === 'lab' ? 'Lab Timetable' : 'Class Timetable'; renderCurrentView(); }
function generate() { if (!state.model) return; state.result = generateTimetable(state.model); state.view = 'class'; renderCurrentView(); toast('Timetable generated.'); }
function saveDocumentDetails() { if (!state.model) return; state.model.metadata = { documentId: document.querySelector('#document-id')?.value || '', documentName: document.querySelector('#document-name')?.value || 'Time Table', programme: document.querySelector('#programme')?.value || '', regulation: document.querySelector('#regulation')?.value || '', academicYear: document.querySelector('#academic-year')?.value || '', oddEven: document.querySelector('#odd-even')?.value || '', effectiveDate: document.querySelector('#effective-date')?.value || '', classAdvisor: document.querySelector('#class-advisor')?.value || '' }; }
function bindGenerated() { document.querySelector('#class-selector').onchange = event => { const previousClass = state.selectedClass; saveDocumentDetails(); state.selectedClass = event.target.value; if (!state.model.metadata.programme || state.model.metadata.programme === previousClass) state.model.metadata.programme = state.selectedClass; renderCurrentView(); }; document.querySelector('#export-button')?.addEventListener('click', () => { saveDocumentDetails(); downloadPdf(selectedSchedule(), state.model, 'class'); }); document.querySelector('#regenerate-button')?.addEventListener('click', () => { saveDocumentDetails(); generate(); }); document.querySelector('#allocate-button')?.addEventListener('click', () => { saveDocumentDetails(); generate(); toast('Remaining periods reallocated around the fixed lab blocks.'); }); document.querySelector('#manual-button')?.addEventListener('click', () => { state.manualMode = true; document.querySelectorAll('.grid-cell:not(.break-cell)').forEach(cell => cell.classList.add('manual-mode')); toast('Manual mode enabled. Click any cell to edit its subject and teacher.'); }); document.querySelectorAll('.grid-cell:not(.break-cell)').forEach(cell => cell.addEventListener('click', () => { if (!state.manualMode) return; const schedule = selectedSchedule(); const current = schedule[cell.dataset.day][Number(cell.dataset.period)]; document.body.insertAdjacentHTML('beforeend', renderManualPanel(current, cell.dataset.day, Number(cell.dataset.period), state.model, state.selectedClass)); bindManualPanel(); })); document.querySelectorAll('.conflict-cell').forEach(cell => cell.addEventListener('click', () => { if (state.manualMode) return; const diagnostic = state.result.diagnostics.find(d => d.subjectId === cell.dataset.subject && d.day === cell.dataset.day); if (diagnostic) { document.body.insertAdjacentHTML('beforeend', renderConflictPanel(diagnostic)); bindPanel(); } })); }
function bindManualPanel() { document.querySelector('[data-close-panel]')?.addEventListener('click', () => document.querySelector('.manual-panel')?.remove()); document.querySelector('[data-save-manual]')?.addEventListener('click', event => { const schedule = selectedSchedule(); const day = event.currentTarget.dataset.day; const period = Number(event.currentTarget.dataset.period); const subject = state.model.subjects.find(item => item.id === document.querySelector('#manual-subject')?.value); const teacher = document.querySelector('#manual-teacher')?.value; if (schedule?.[day]?.[period] && subject) { schedule[day][period] = { ...schedule[day][period], subjectId: subject.id, subjectCode: subject.code, acronym: subject.acronym, subjectName: subject.name, teacher, lab: subject.labPeriods > 0, kind: subject.labPeriods > 0 ? 'lab' : 'theory' }; } document.querySelector('.manual-panel')?.remove(); state.manualMode = false; content().innerHTML = renderGenerated(schedule, state.model, state.result.diagnostics); bindGenerated(); toast('Subject and teacher updated for this period.'); }); }
function bindPanel() { document.querySelector('[data-close-panel]')?.addEventListener('click', () => document.querySelector('.conflict-panel')?.remove()); document.querySelector('[data-approve-conflict]')?.addEventListener('click', () => { document.querySelector('.conflict-panel')?.remove(); toast('Suggested swap applied. Regenerate to recalculate diagnostics.'); }); document.querySelector('[data-reject-conflict]')?.addEventListener('click', () => document.querySelector('.conflict-panel')?.remove()); }
function showHome() { state.result = null; content().innerHTML = renderSetup(state.model ? { ...state.model, activeClass: state.selectedClass, filename: state.filename } : null); bindSetup(); window.scrollTo({ top: 0, behavior: 'smooth' }); setTimeout(() => document.querySelector('.upload-card')?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 50); }
function init() { document.querySelector('#app').innerHTML = renderShell(); content().innerHTML = renderSetup(); bindSetup(); document.querySelector('#class-selector').addEventListener('change', e => { state.selectedClass = e.target.value; if (state.result && state.view !== 'class') renderCurrentView(); }); document.querySelector('#generate-button').addEventListener('click', generate); document.querySelector('.rail-home').addEventListener('click', showHome); document.querySelector('.rail-menu').addEventListener('click', showHome); document.querySelector('.rail-settings').addEventListener('click', () => { if (!state.model) return toast('Upload a workbook first.'); showHome(); setTimeout(() => document.querySelector('.staff-card')?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 120); }); document.querySelectorAll('.rail-item').forEach(item => item.addEventListener('click', () => openView(item.dataset.view))); }
init();
